#!/bin/sh
code --install-extension AmazonWebServices.aws-toolkit-vscode
code --install-extension bungcip.better-toml
code --install-extension alefragnani.Bookmarks
code --install-extension lixquid.calculator
code --install-extension wmaurer.change-case
code --install-extension lucax88x.codeacejumper
code --install-extension orepor.color-tabs-vscode-ext
code --install-extension fabiospampinato.vscode-diff
code --install-extension usernamehw.errorlens
code --install-extension mksafi.find-word-at-cursor
code --install-extension reduckted.vscode-gitweblinks
code --install-extension hasanali.gitignore-templates
code --install-extension eamodio.gitlens
code --install-extension heaths.vscode-guid
code --install-extension octref.vscode-json-transform
code --install-extension quicktype.quicktype
code --install-extension mechatroner.rainbow-csv
code --install-extension stkb.rewrap
code --install-extension 74th.scrollkey
code --install-extension Tyriar.sort-lines
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension HaaLeo.timing
code --install-extension tomoki1207.pdf
code --install-extension jrebocho.vscode-random
code --install-extension redhat.vscode-yaml
code --install-extension golang.Go
code --install-extension jinliming2.vscode-go-template
code --install-extension v4run.gotimeformat
